name: 'dbt_repo'
version: '1.0.0'
config-version: 2

profile: 'dev'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_repo:
    staging:
      +materialized: table
      +transient: true
      +schema: STAGING
    marts:
      dimensions:
        +materialized: table
        +schema: DIMENSIONS
      facts:
        +materialized: incremental
        +schema: FACTS
      aggregates:
        +materialized: table
        +schema: AGGREGATES
